name: shockwave_demo
description: Shockwave demonstration.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
